[package]
name = "handler"
version = "0.1.0"
edition = "2021"
authors = [
    "Heath Stewart (https://github.com/heaths)",
]
description = "Azure Functions implementation in Rust"
rust-version = "1.82"
publish = false

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.4.2", features = ["server"] }

[dev-dependencies]
clap = { version = "4.5.47", features = ["cargo"] }
reqwest = "0.12.23"
