name: cd
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/CODEOWNERS
      - "**/*.md"

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 1
  RUSTFLAGS: -Dwarnings

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        # Install everything in rust-toolchain.toml and print versions.
        run: rustup show
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          zip "$RUNNER_TEMP/deploy.zip" host.json hello/function.json target/x86_64-unknown-linux-musl/release/handler
      - name: Log into staging environment
        uses: Azure/login@v2
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Deploy to staging environment
        id: deploy-test
        run: |
          az functionapp deployment source config-zip --subscription "$AZURE_SUBSCRIPTION_ID" -g "$AZURE_RESOURCE_GROUP" -n "$AZURE_FUNCTIONAPP_NAME" --slot test --src "$RUNNER_TEMP/deploy.zip"
          az functionapp show --subscription "$AZURE_SUBSCRIPTION_ID" -g "$AZURE_RESOURCE_GROUP" -n "$AZURE_FUNCTIONAPP_NAME" --slot test --output json | jq -r '"AZURE_HOSTNAME=" + .defaultHostName' >> "$GITHUB_OUTPUT"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
      - name: Test staging environment
        run: |
          if [[ `curl --no-progress-meter --verbose "$AZURE_HOSTNAME/api/hello"` != 'Hello, world!' ]]; then
            exit 1
          fi
        env:
          AZURE_HOSTNAME: ${{ steps.deploy-test.outputs.AZURE_HOSTNAME }}
