name: cd
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/CODEOWNERS
      - "**/*.md"

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 1
  RUSTFLAGS: -Dwarnings

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        # Install everything in rust-toolchain.toml and print versions.
        run: rustup show
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          zip deploy.zip host.json hello/function.json target/x86_64-unknown-linux-musl/release/handler
